### ISSUE TITLE
Recursive addition of test directories

### ISSUE THREAD

**Issue by scottclowe** [MOxUnit/MOxUnit#16]
It would be good to have an option (at least) for recursive addition of test directories into the testsuite.

I for one would like to organize my `tests/` folder to match the hierarchy in the package folder, and the only way this is feasible is if I can do recursive addition of directories into the testsuite.

It would make sense for it to be possible to enable/disable recursion, so I think this should be available as an input to both `@MOxUnitTestSuite/addFromDirectory.m` and `moxunit_runtests.m`.

**Comment by nno** [comment]
Thanks, I like the idea.
What are your thoughts on how to achieve this? How about adding an option `-recursive` to `moxunit_runtests.m`, and a fourth argument `recursive` to `@MOxUnitTestSuite/addFromDirectory.m`?

**Comment by scottclowe** [comment]
Yes, pretty much exactly that.
And a `-r` shorthand alias for `-recursive` might not be a bad idea too.
Maybe the argument to `@MOxUnitTestSuite/addFromDirectory.m` could be better named as `allow_recursion` or something similar to indicate the value is boolean?

**Comment by nno** [comment]
Addressed by #17.
