### ISSUE TITLE
Commenting style suggestions/rationale

### ISSUE THREAD

**Issue by jwleblan** [MOxUnit/MOxUnit#29]
While working on changes as part of a pull request to improve assertExceptionThrown.m I noticed some places that comments could be improved.  That is, made more clear and readable.  Few things can be more annoying that someone deviating from a projects commenting style/guidelines without discussion so here goes...

I feel as though the projects commenting style can be altered to improve readability/clarity.  The suggested changes (or at least allowances) are all based on making things more explicit.  Specifically:

- Place all comments above `function …` .  This prevents a functions documentation from being split between two blocks of executable code and groups the executable code into a single coherent block.  It also allows one to collapse a functions implementation while maintaining that functions documentation.  Finally, it prevents users from treating the function declaration itself as the documentation of its prototype rather than the one provided in the comments.  The commented prototype is often much more expressive (see below)
- Use ""<>"" rathe than ""[]"" to indicate optional parameters.  Square brackets indicate concatenation in Matlab, and this could lead to confusion for less experienced users.
- All caps section headings.  The use of all capitols for section headings, and the explicit inclusion of a SYNTAX heading, could make documentation more easily parseable by eye.
- The addition of a PURPOSE section.  A functions summary description (available in the first comment line) is often insufficient for describing what a function is for.  A dedicated purpose section would allow for this, and its inclusion would encourage better documentation.
- The addition of an ASSUMPTIONS section.  A place to explicitly state assumptions.  For example, functions often do not provide input argument checks.  This is a good thing, for "internally facing functions" as it allows the code to execute faster, but when this is the case it ought to be explicitly stated.
- A visual "-" would be helpful in indicating where multi-line parameter descriptions start.
- 80-character bars as a visual indicator that we expect comments to be formatted within this width limitation.
- Place comments inside a block comment to allow them to be collapsed in more advanced editors

The only downside I can see to these changes is that Octave has a limitation in its help parser that fails to recognize block comments.  One can either remove this feature, or accept Octave's limitation until it gets fixed.

An example of these ideas being put into practice can be found in assertExeptionThrown.m in the aforementioned PR.

**Comment by nno** [comment]
@jwleblan, thanks for the comments and ideas. There are many commenting styles, all with their pros and cons. Let me try to explain the rationale for the current commenting style by going through your points:

> Place all comments above ``function …`` . This prevents a functions documentation from being split between two blocks of executable code and groups the executable code into a single coherent block. It also allows one to collapse a functions implementation while maintaining that functions documentation. Finally, it prevents users from treating the function declaration itself as the documentation of its prototype rather than the one provided in the comments. The commented prototype is often much more expressive (see below)

In my experience, the prototype in the documentation can usually be just a copy-paste of the code. I have encountered very few cases where this is not the case. MOxUnit follows the documentation style used In the (much larger) CoSMoMVPA project [see https://github.com/CoSMoMVPA/CoSMoMVPA/tree/master/mvpa]. There, maybe 2 out of >100 functions required more than one line for the prototype.
Keeping the prototype and code close together (i.e. ``function ...`` at the top) means that it's easy to spot if the two mismatch.

> Use ""<>"" rathe than ""[]"" to indicate optional parameters. Square brackets indicate concatenation in Matlab, and this could lead to confusion for less experienced users.

Good point, thanks.

> All caps section headings. The use of all capitols for section headings, and the explicit inclusion of a SYNTAX heading, could make documentation more easily parseable by eye.

This may be a matter of preference, but I PERCEIVE WORDS IN CAPITOLS AS SHOUTING and therefore distracting. To make the documentation parseable, we currently use indentation.

> The addition of a PURPOSE section. A functions summary description (available in the first comment line) is often insufficient for describing what a function is for. A dedicated purpose section would allow for this, and its inclusion would encourage better documentation.
> The addition of an ASSUMPTIONS section. A place to explicitly state assumptions. For example, functions often do not provide input argument checks. This is a good thing, for "internally facing functions" as it allows the code to execute faster, but when this is the case it ought to be explicitly stated.

I've been using a 'Notes' for all such miscellaneous items. I don't have problems with such sections, though in my experience I have the impression that the purpose or assumptions, if necessary, can be specified in addition to a one-line explanation at the top; the arguments; and examples; or in the Notes section. 

> A visual "-" would be helpful in indicating where multi-line parameter descriptions start.
80-character bars as a visual indicator that we expect comments to be formatted within this width limitation.

I try to limit line length to 75. My matlab editor already shows a vertical line with this limit, so I don't see the need for a visual '-' bar. It just adds work to keep these lines there.

> Place comments inside a block comment to allow them to be collapsed in more advanced editors. The only downside I can see to these changes is that Octave has a limitation in its help parser that fails to recognize block comments. One can either remove this feature, or accept Octave's limitation until it gets fixed.

I'm not sure if I understand the point about Octave's limitation....

best,
Nick

**Comment by jwleblan** [comment]
Thanks for the feedback.  This was mostly to indicate *why* I made certain design decisions, and as a way of clarifying my own thinking on the matter.

The Octave limitation, however, is important.  The code below emphasizes the problem.
```matlab
% This is a regular comment
%{
% This is part of a multi-line comment.
These lines will never appear using Octave's help command because of a limitation in how help.m parses.  The "regular" comment above will appear.
%}
```

~Joel

**Comment by nno** [comment]
@jwleblan thanks for explaining the Octave limitation. It would then be better to not use code blocks in my opinion.
