### ISSUE TITLE
Doubt: Is it possible to write test cases using Object-oriented syntax?

### ISSUE THREAD

**Issue by abravalheri** [MOxUnit/MOxUnit#34]
Do MOxUnit recognize the same Object-oriented syntax for test suites that the matlab-xunit counterpart?  ([example](https://github.com/psexton/matlab-xunit/blob/master/doc/examples_general/TestUsingTestCase.m)).
Or even another OO-syntax?

(The README page seems to indicate that it is possible, but I could not find the documentation about how to do it...)

**Comment by nno** [comment]
It should be possible to write tests in O-O syntax; indeed, most of MOxUnit is written using O-O syntax. But Octave does not support all O-O syntax that is supported by Matlab, so depending on how you write the code, not all code you write may run on Octave.

**Comment by abravalheri** [comment]
Let me see if I understand...

So it should be possible (theoretically) to write a test:

```matlab
# file: tests/TestTheTuth.n
classdef TestTheTuth< MOxUnitTestCase
  methods
    function testPass
      assert(true);
    end
  end
end
```

**Comment by nno** [comment]
It seems that it's not possible to subclass the classes using classdef syntax. I've added a note in the README.me file. 

Would you like to extend tests written using Matlab's unit test framework? 
http://it.mathworks.com/help/matlab/ref/matlab.unittest.html
It may be possible to write some wrapper code to support those as well; please let me know.

**Comment by nno** [comment]
For now I'm closing the issue. If more clarification is needed, please re-open. If you want to extend Matlab's unit test framework, please open a new issue.
