### ISSUE TITLE
Readme.md abiguity 

### ISSUE THREAD

**Issue by homocomputeris** [MOxUnit/MOxUnit#35]
Hi,
The manual installation part of the Readme is not very clear: 

> On the Matlab or GNU Octave prompt, cd to the MOxUnit root directory, then run:

Actually, it should be something like this, with the second-lever directory:
```
git clone https://github.com/MOxUnit/MOxUnit.git
cd ./MOxUnit/MOxUnit % this is not MOxUnit root
moxunit_set_path()
```

**Comment by nno** [comment]
Thanks for the report.
I just modified the README, see #37. Does that clarify the documentation?

**Comment by homocomputeris** [comment]
Thanks, I believe now it reads better.
