### ISSUE TITLE
Run tests in random order

### ISSUE THREAD

**Issue by Remi-Gau** [MOxUnit/MOxUnit#84]
Would it be possible to add an option to run the tests of a test suite in a random order? 

This may help detect test pollution : tests are not independent, the results of a test may depend on the outcome of a test that was run before. 

Running tests in a different order may help detect this type of test pollution. It is not perfect but if the tests are run regularly it should eventually catch the tests inter dependence.

**Comment by nno** [comment]
Would this PR address your idea?

https://github.com/MOxUnit/MOxUnit/pull/86

**Comment by nno** [comment]
This has been merged into the main branch. @Remi-Gau If this does not provide the functionality you had in mind, please re-open this issue.

**Comment by Remi-Gau** [comment]
Awesome.
Thanks.
Will test that in my CI workflows (and I would not be surprised if it showed that my tests are not actually independent).
