### ISSUE TITLE
Improve doc to add CI setup examples to run with github 

### ISSUE THREAD

**Issue by Remi-Gau** [MOxUnit/MOxUnit#85]
I have a template repo and a cookie cutter with things I could extract to add to the doc here describing how to do it. 

https://github.com/Remi-Gau/template_matlab_analysis

Let me know it there is some interest.

**Comment by nno** [comment]
Greeting: I think this could be a useful addition. So from my side there is definitely interest.

**Comment by Remi-Gau** [comment]
Oh another thing: do you want me to show how to use Mocov in those examples or do you prefer to have those on the mocov repo?

Note that the workflow already present in the .github folder does include using mocov.

**Comment by Remi-Gau** [comment]
> > Oh another thing: do you want me to show how to use Mocov in those examples or do you prefer to have those on the mocov repo?
> 
> I would think that it is unlikely that people would use MOCov without MOxUnit, so I think it is fine to have the documentation in MOxUnit. In the MOCov documentation, I could add a pointer to the MOxUnit documentation. What do you think?

Makes sense to me too. Just wanted to. Make sure we saw things the same way.

**Comment by Remi-Gau** [comment]
> I'm not sure If I understand what you consider as two options. Do you suggest to to add more documentation on how to run tests on Octave? 

Yes. The easy way is to just use the pre-made github action. The more complex way is to set up your own workflow. 

I think in the vast majority of cases the preset action works well but I have had some cases where I created my own workflow if some dependencies with mex files needed to first be compiled for Octave.

**Comment by nno** [comment]
That sounds good to me. Thanks.

**Comment by nno** [comment]
That sounds good. Are you able to reproduce the ci issues on Windows locally?

**Comment by Remi-Gau** [comment]
> That sounds good. Are you able to reproduce the ci issues on Windows locally?

Not tried before I left for a month long trip away from it. 🤦🏾

**Comment by nno** [comment]
I think `MOcov/@MOcovMFileCollection/rewrite_mfiles.m` is causing the issue:
```
pat=sprintf('mocov_line_covered(%d,''%s'',%%d,1);',k,rel_fn);
decorator=@(line_number) sprintf(pat,line_number);
```
Here `pat` is based on the relative filename, which on Windows may contain backslashes. It then becomes part of the pattern which is used to build the line number. It seems it would not be too hard to fix.

**Comment by Remi-Gau** [comment]
will update this PR to take into account the recent fix on mocov
